services:
  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example_root_password
      - MYSQL_PASSWORD=example_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:31
    container_name: nextcloud_app
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud_data:/var/www/html/data
      - ./config:/var/www/html/config
      - ./custom_apps:/var/www/html/custom_apps
      - ./themes:/var/www/html/themes
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - MYSQL_PASSWORD=example_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    depends_on:
      - db

  caddy:
    image: caddy:2
    container_name: nextcloud_caddy
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  db_data:
  nextcloud_data:
  caddy_data:
  caddy_config:
