<?php
$CONFIG = array (
  'instanceid' => 'nextcloud',
  'passwordsalt' => 'votre_salt_ici',
  'secret' => 'votre_secret_ici',
  'trusted_domains' => 
  array (
    0 => '{$DOMAIN_CLOUD}',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '31.0.5.1',
  'overwrite.cli.url' => 'https://{$DOMAIN_CLOUD}',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'example_password',
  'installed' => true,
  'maintenance' => false,
  'default_phone_region' => 'FR',
  'maintenance_window_start' => 1,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'redis' => array(
    'host' => 'redis',
    'port' => 6379,
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => 587,
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'votre_email@gmail.com',
  'mail_domain' => 'gmail.com',
  'mail_smtpname' => 'votre_email@gmail.com',
  'mail_smtppassword' => 'votre_mot_de_passe_app',
); 